--liquibase formatted sql

-- changeset clean_validation_results:1
CREATE TABLE meta.clean_validation_results 
(
  validation_result_id STRING PRIMARY KEY COMMENT "Primary Key for validation result, generated by the system",
  unique_key STRING COMMENT "Primary key of the record that has been validated", 
  unique_key_column STRING COMMENT "Name of column to which the primary key belongs in the source table",
  rule_name STRING COMMENT "Name of the rule that has been validated",
  batch_id INT COMMENT "Monotonically increasing ID of a batch of records that have been validated",
  batch_record_count BIGINT COMMENT "Number of records in a batch",
  source_table_name STRING COMMENT "Name of the table from which records were taken for validation",
  md_validation_status STRING COMMENT "Result of validaiton, either SUCCESS or INVALID",
  md_metadata STRING COMMENT "Start and end time used for subsetting source data into a batch",
  md_source_name STRING COMMENT "Table name of source data",
  md_created_datetime TIMESTAMP COMMENT "Date and time of record creation",
  md_updated_datetime TIMESTAMP COMMENT "Date and time of record update",
  md_deleted_datetime TIMESTAMP COMMENT "Date and time of record deletion",
  md_change_status STRING COMMENT "Change status of the record"
)
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.columnMapping.mode' = 'name',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7'
);
