name: Databricks Bundle Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ "pilot"]
  workflow_dispatch:

permissions:
    id-token: write      # needed for OIDC
    contents: read


jobs:
  deploy:
    runs-on: ubuntu-latest

    # This ties the job to a GitHub Environment named dev/test/prod
    # and must match the `environment:` part of your federation policy subject.
    environment: ${{ github.ref_name }}


    env:
      # DAB target name (we made targets dev/test/prod in databricks.yml)
      TARGET: ${{ github.ref_name }}

      # Tell Databricks CLI to use GitHub OIDC
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: https://dbc-44d88950-fd99.cloud.databricks.com/
      DATABRICKS_CLIENT_ID: a0e846697-a5c3-47f3-975c-229d2770dcff

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle
        run: |
          databricks bundle validate --target dev

      - name: Plan bundle
        run: |
          databricks bundle plan --target dev
